# Import Datasets

In [5]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Loding Dataset

In [6]:
data=pd.read_csv("StudentsPerformance.csv")
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Checking Null Values

In [7]:
data.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

# Summary of Dataset

In [8]:
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# Create Target

In [56]:
data['average_score'] = (
    data['math score'] +
    data['reading score'] +
    data['writing score']
) / 3

In [57]:
data['target'] = (data['average_score'] >= 50).astype(int)

# Encode categorical columns

In [58]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_cols = [
    'gender',
    'race/ethnicity',
    'parental level of education',
    'lunch',
    'test preparation course'
]

for col in categorical_cols:
    data[col] = le.fit_transform(data[col])

In [59]:
X = data.drop('target', axis=1)

In [64]:
X = data.drop(['target', 'average_score'], axis=1)  
y = data['target']

# Train-Test-split

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scaling

In [66]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model Training

# Decision Tree

In [67]:
from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier()
dt_model

DecisionTreeClassifier()

In [68]:
from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier(max_depth=5, criterion='gini',random_state=42)
dt_model
# Model fitting:
dt_model.fit(X_train, y_train)
# Model predict:
dt_pred=dt_model.predict(X_test)
# Model evaluation:
from sklearn.metrics import accuracy_score
dt_acc=accuracy_score(y_test,dt_pred)
print(dt_acc)

0.985

In [69]:
print(X.columns)         # to check if average_score is not in X.

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

# KNN

In [74]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=7,metric='euclidean',weights='uniform')
knn_model

KNeighborsClassifier(metric='euclidean', n_neighbors=7)

In [70]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=7,metric='euclidean',weights='uniform')
knn_model
# model fitting
knn_model.fit(X_train_scaled, y_train)
#model predict
knn_pred=knn_model.predict(X_test_scaled)
#model evaluation
from sklearn.metrics import accuracy_score
knn_acc=accuracy_score(y_test,knn_pred)
print(knn_acc)

0.945

# Logestic Regression

In [71]:
from sklearn.linear_model import LogisticRegression
lr_model=LogisticRegression(max_iter=1000, random_state=45)
lr_model

LogisticRegression(max_iter=1000, random_state=45)

In [72]:
from sklearn.linear_model import LogisticRegression
lr_model=LogisticRegression(max_iter=1000, random_state=45)
lr_model
# model fitting
lr_model.fit(X_train_scaled, y_train)
#model predict
lr_pred=lr_model.predict(X_test_scaled)
#model evaluation
from sklearn.metrics import accuracy_score
lr_acc=accuracy_score(y_test,lr_pred)
print(lr_acc)

0.985

# Random forest

In [77]:
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier(max_depth=3,random_state=42)
rf_model

RandomForestClassifier(max_depth=3, random_state=42)

In [73]:
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier(max_depth=3,random_state=42)
# Model fitting:
rf_model.fit(X_train, y_train)
# Model predict:
rf_pred=rf_model.predict(X_test)
# Model evaluation:
from sklearn.metrics import accuracy_score
rf_acc=accuracy_score(y_test,rf_pred)
print(rf_acc)

0.97

# Naive Bayes

In [78]:
from sklearn.naive_bayes import GaussianNB
nb_model=GaussianNB()
nb_model

GaussianNB()

In [79]:
from sklearn.naive_bayes import GaussianNB
nb_model=GaussianNB()
nb_model
# Model fitting:
nb_model.fit(X_train, y_train)
# Model predict:
nb_pred=nb_model.predict(X_test)
# Model evaluation:
from sklearn.metrics import accuracy_score
nb_acc=accuracy_score(y_test,nb_pred)
print(nb_acc)

0.985

# SVM-SVClassifier

In [80]:
from sklearn.svm import SVC
svm_model=SVC(kernel='rbf',C=1, random_state=42)    # always c=0 or 1
svm_model

SVC(C=1, random_state=42)

In [81]:
# Model fitting:
svm_model.fit(X_train, y_train)
# Model predict:
svm_pred=nb_model.predict(X_test)
# Model evaluation:
from sklearn.metrics import accuracy_score
svm_acc=accuracy_score(y_test,svm_pred)
print(svm_acc)
svm_model

0.985

SVC(C=1, random_state=42)

# Model comparision

In [82]:
model_accuracies={
    "DT":dt_acc,
    "RF":rf_acc,
    "svm":svm_acc,
    "lr":lr_acc,
    "nb":nb_acc,
    "knn":knn_acc,
}
model_accuracies

{'DT': 0.985, 'RF': 0.97, 'svm': 0.985, 'lr': 0.985, 'nb': 0.985, 'knn': 0.945}

# Best Model

In [83]:
# best model
best_model_name=max(model_accuracies,
                   key=model_accuracies.get)
best_accuracy=model_accuracies[best_model_name]
print(f"\n Best Model: {best_model_name} with accuracy of {best_accuracy:.4f}")

 Best Model: DT with accuracy of 0.9850

# Model saving

In [84]:
import joblib
joblib.dump(dt_model,"heart_model.pkl")
joblib.dump(scaler,"sacler.pkl")

['sacler.pkl']