# This is Hands on session of Feature Engieerig in Machine Learning

dataset link : https://www.kaggle.com/datasets/huyngohoang/housingcsv

In [3]:
import numpy as np
import pandas as pd
df=pd.read_csv('Housing.csv')
df=df.select_dtypes(include=np.number)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0

In [4]:
#perform Absolute maximum scaling
max_abs=np.max(np.abs(df), axis=0)#
scaled_df=df/max_abs
scaled_df.max

<bound method DataFrame.max of        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0      -0.982951  0.902980            0.788462     0.022380        0.020016
1      -0.982871  0.902503            0.403846     0.180544        0.171606
2      -0.983032  0.902265            1.000000     0.037309        0.029480
3      -0.983112  0.902265            1.000000     0.032401        0.036462
4      -0.983112  0.902265            1.000000     0.041378        0.043445
...          ...       ...                 ...          ...             ...
20635  -0.973784  0.941120            0.480769     0.042345        0.058029
20636  -0.974749  0.941359            0.346154     0.017726        0.023274
20637  -0.974829  0.939928            0.326923     0.057325        0.075252
20638  -0.975633  0.939928            0.346154     0.047304        0.063460
20639  -0.974990  0.938498            0.307692     0.070829        0.095578

       population  households  median_income  median_house_value
0        0.009024    0.020717       0.555010            0.905198
1        0.067289    0.187110       0.553423            0.716999
2        0.013901    0.029102       0.483823            0.704199
3        0.015638    0.036008       0.376204            0.682599
4        0.015834    0.042585       0.256412            0.684399
...           ...         ...            ...                 ...
20635    0.023681    0.054258       0.104019            0.156200
20636    0.009977    0.018744       0.170452            0.154200
20637    0.028222    0.071194       0.113333            0.184600
20638    0.020767    0.057382       0.124479            0.169400
20639    0.038871    0.087142       0.159239            0.178800

[20640 rows x 9 columns]>

In [ ]:
#perform standalization
from sklearn.preprocessing import StandardScaler
scaler=Standardscaler()
scaled_df=scaled.fit_transform(df)
x=pd.DataFrame(scaled_df)

In [5]:
#perform normalization
from sklearn.preprocessing import StandardScaler
Scaler=StandardScaler()
Scaler.fit_transform(df)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0

In [8]:
from sklearn.preprocessing import RobustScaler
Scaler=RobustScaler()
Scaler_data=Scaler.fit_transform(df)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0